### PR TITLE
Creates docker file for running this server.

### PR DESCRIPTION
**Pull request by johnbradley**
Adds Dockerfile that will create a container at https://quay.io/repository/dukegcb/bespin-job-watcher. To override configuration create a volume at `/usr/src/app/config.json`.

Also includes changes to config so bespin will be specified as a single url config to match up with bespin-web.

### CODE REVIEW

**Comment by johnbradley** [comment]
Wait for https://github.com/Duke-GCB/bespin-job-watcher/pull/2  before committing this.

**Review by dleehr — COMMENTED** [review]
Dockerfile builds and attempts to start server, but config is hard-coded. 

Is the plan to read config out of environment?

**Comment by johnbradley** [comment]
> Is the plan to read config out of environment?

We will override configuration by creating a volume at `/usr/src/app/config.json`.
This is the same approach we will use for certs.

**Comment by dleehr** [comment]
OK. Could use a note on that in the README then

**Pull request merged**
